spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fd_calculator
    username: root
    password: root@fintech
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  spring:
    profiles:
      active: mock


pricing:
  api:
    url: http://localhost:8080

server:
  port: 8081

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    filter: true
    try-it-out-enabled: true
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json


