spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fd_calculator
    username: root
    password: root@fintech
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  spring:
    profiles:
      active: mock


pricing:
  api:
    url: http://localhost:8080
server:
  port: 8081


